### ISSUE TITLE
Log data

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#110]
_From @JackMostow on February 1, 2017 20:52_

LOGGING in RoboTutor Development Plan:  COMPONENTS

See 2/16/17 updated versions of "WHAT TO LOG" [https://docs.google.com/document/d/1VA5f5xN7WnqJZSdQlj2AIGGFlkM7Z3XA0u3kOfLlheQ/edit?usp=sharing] and "What metrics would be useful to compute automatically?" in XPRIZE - Home > Design Discussion > LOGGING and ANALYSIS [https://drive.google.com/open?id=0B2NLAaJNgy1CZlZKeHBrbTExZXM](url)

Previous brief description: -- see "WHAT TO LOG" for details and update:

Generic events (e.g. tap screen objects, animation graph transitions)
Records based on the DataShop logging specification [Koedinger, Baker, Cunningham, Skogsholm, Leber, & Stamper, 2010]:
•Selection – the object being acted on
•Action – the type of action being performed
•Input – the parameters of the action
•State – A description of the game state just before the action was taken:  name of animation graph and state therein are necessary but do not capture entire state -- e.g. values of other state variables
Activity-specific -- explicit logging in the activity, vs. generic logging in the architecture
(Changes to) difficulty factor values
Activity parameter values
Item from data source, including stimulus, target, and distractors
(Each) response to item and whether correct, incorrect, or hesitation
Glyphs
Audio input
ASR output
LISTENER input and output
Camera input

_Copied from original issue: synaptek/RoboTutor#202_

**Comment by kevindeland** [comment]
Resolved in a previous commit.
