### ISSUE TITLE
Use BubblePop for sequence completion, construction, unscrambling, and cloze tasks

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#235]
With little or no change to BubblePop, we can use it to implement sequence completion, construction, and unscrambling tasks.

Sequence completion:

•	The Missing Number game, e.g. 2  4 __ 8, is an example of a completion task.

•	BubblePop can implement cloze questions!!  Just use the incomplete sentence as stimulus and words that violate syntactic, semantic, or contextual constraints as distractors.  They won't be as pretty as our prototype but we can include them in our resubmission.  Yay!

Heterogeneous data sources will let us insert cloze questions between story pages.

•	Tapping the correct bubble moves its letter/digit/syllable/word to the first ___ in the stimulus sequence, which may be at the end, e.g. “Once upon __”, where the correct answer is “a”.

•	BubblePop then advances to the next item, whose stimulus in this case is “Once upon a ___”.

•	BubblePop only accepts correct responses, so the data source generator can simply generate the appropriate sequence of visual stimuli, e.g.:
o	__
o	Once __
o	Once upon __
o	Once upon a __
o	Once upon a time __
o	Etc.

Sentence construction:

•	The data source generator can draw randomly from narrated stories to select sentences short enough to fit in the stimulus box (which allows multiple lines), and specify the corresponding portion of the narration as the audio stimulus -- which BubblePop will need to allow as audio stimuli.

•	A sentence construction task may start from scratch with the visual stimulus “__”, which isn’t enough context to pick the first word, but can telegraph the answer by capitalizing only one word (“Once”) to teach kids to capitalize the first word of a sentence.  DuoLingo uses this trick.

•	Subsequent stimuli exercise syntax and semantics by making the kid figure out which word fits next.

•	For a sequence unscrambling task, the choices are some or all elements of the original sequence.
As each element is placed, it can be removed from the choices in the next step, till only one is left.

•	For a less constrained construction task, the correct answer for item i is sequence element i, and the distractors don't need to be sequence elements.

BubblePop activities to fill in the missing letter(s) or syllable(s) in a word will need BubblePop to accept an audio “say” stimulus different from the visual “show” stimulus, or in general to specify a parameterized audio prompt for each item.

o	E.g. for the visual stimulus “C __ T” we’d want the audio stimulus “CAT” and a prompt like “Tap the missing letter in <WORD>” or “Tap the missing letter in” + “CAT”.  We need the same sort of capability for prompts like “Find another A”.

**Comment by kevindeland** [comment]
Resolved for number sequence completion. Cloze questions were resolved elsewhere.
