### ISSUE TITLE
1.8.9.1 Eliminate rating menu

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#313]
Rating menu wastes time.  Eliminating it will please Judith ;-).

1. Already moved Exit to activity picker.

2. Move Redo to activity picker.  Either:
a. Disable it until kid completes an activity in the session.
b. Keep track of last activity in previous session.
c. Don't worry about it.

3. Change "Let RoboTutor pick."  Either:
a. Eliminate it, especially if seldom used.
b. Change it to pick randomly rather than always pick a story.
c. Change it to pick whichever content is least completed.

4. Check whether Rating menu triggers any Mentor messages.  I don't think it does.

**Comment by kevindeland** [comment]
Resolved in a previous commit.
