### ISSUE TITLE
NEW TUTOR: Number Discrimination app (Greater/Less Than)

### ISSUE THREAD

**Issue by judithodili** [RoboTutorLLC/RoboTutor#328]
Using Bubble pop for number discrimination is not the most intuitive way to teach this skill. It's better than nothing, but we can definitely design something simple to help really teach this skill. We should not only have the kids comparing numbers but comparing quantities of everyday objects (not just dots) that they are familiar with. I'm going to follow this post with a bunch of screenshots from other apps to help us get started.

**Comment by kevindeland** [comment]
Resolved.
