### ISSUE TITLE
NEW TUTOR: Word Spelling (not writing activity)

### ISSUE THREAD

**Issue by judithodili** [RoboTutorLLC/RoboTutor#329]
With the current tutors, the kids go from hearing a word and picking it out (in Bpop and Akira), to hearing a word and writing it... which is not only testing their ability to spell but ALSO their ability to write it as well. We can definitely benefit from a word spelling tutor .... hopefully with TTS incorporated but at least with corrective feedback. Below are some screenshots apps for inspiration.

**Comment by kevindeland** [comment]
Resolved in a previous commit.
