### ISSUE TITLE
DISCUSS comprehension questions

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#332]
We already have specific issues for cloze, picture-matching, and generic wh- questions.
This issue is for discussion that cuts across them and other types of questions to add, if any.

Let's start with a reality check on comprehension questions, in terms of how and why we will use them:

1. A (perhaps the) main reason is to prepare kids for the EGRA by giving them practice in answering comprehension questions.
2. Another reason to insert comprehension checks is as a forcing function simply to get kids to pay attention to story meaning while they read.
3. A related reason is to scaffold comprehension by triggering comprehension processes such as constructing situation models, drawing inferences, and thinking about context.
4. Some questions – e.g. open-ended generic wh- questions – are to assist comprehension without assessing it.
5. The wh- questions are also useful practice for EGRA insofar as they resemble EGRA questions, e.g. “Who is this story about?”.
6. Unlike school settings, we are not generating assessments for parents, teachers, or report cards – only for tutorial decisions about what to do next.
7. Should we make kids keep rereading each story until they answer some percentage of comprehension questions?
8. Another use of comprehension assessments is to adjust the level of difficulty of the comprehension questions, e.g. by picking easier or harder distractors in cloze questions.

**Comment by kevindeland** [comment]
Resolved.
