### ISSUE TITLE
1.8.9.1 log crashes

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#353]
Incorporate Shiven's crashlog code from FaceLogin.
Log to where?
a. Separate crash logs? <-- YES
b. PERF logs? -- @eyarzebinski, (how) do you want crashes logged in PERF logs?  I assume probably not.
c. Verbose logs? -- @kevindeland, do you want crashes logged in verbose logs?  I assume not necessarily.

What to log:
a. tablet id
b. timestamps -- both Unix and human-readable
c. sessionid
d. stack trace
e. source code filepath and line
f. configuration filepath and contents

**Comment by kevindeland** [comment]
Fixed in the above comment. Closing.
