### ISSUE TITLE
1.8.9.1 need flag in perf logs for placement test or curriculum

### ISSUE THREAD

**Issue by eyarzebinski** [RoboTutorLLC/RoboTutor#360]
I recall there being a flag in the verbose logs that notes when a student is in placement mode and when a student is not in placement mode anymore. Kevin, can you please reflect that in the perf logs as "placement" or "curriculum" (if not in placement)? If it's a simple thing, would be great to get this in the version going out with crash logging since students will have to take the placement test again. Thanks!

**Comment by kevindeland** [comment]
Resolved in a previous commit.
