### ISSUE TITLE
1.8.9.1 use NTP to update tablet clock?

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#367]
@kevindeland - (Where) should we call NTP to update the tablet clock when it's reset after battery running out?

a. Don't bother.

b. In program that uploads log files to ftp server
+:  already communicates with server
-:  too late after log files are already written

c. In RoboTutor when it launches
+: fixes dates as soon as tablet has Wifi access to village server

**Comment by kevindeland** [comment]
Related to XPrize, thus no longer relevant. Will re-open/re-create if needed in the future.
