### ISSUE TITLE
reimplement RTAssetManager

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#390]
Reverse engineer .jar file
Include version # of assets in name + information about RoboTutor build, date, phase of moon, etc.

**Comment by kevindeland** [comment]
Good news. I found a method to extract the source code from a .jar file, and used said method to get the source code rom RTAssetManager.jar.  So this won't be necessary.

If we need to provide the source code then we can create a new repository to hold it.

**Comment by kevindeland** [comment]
For reference:
https://stackoverflow.com/questions/5107187/extract-source-code-from-jar-file
