### ISSUE TITLE
Broken RTAsset_Publisher link in README.md

### ISSUE THREAD

**Issue by sedflix** [RoboTutorLLC/RoboTutor#418]
The GitHub repo pointed by this doesn't exist now. 
Should we replace this step with instructions to push different kinds of assets to the device?

On similar lines, what do repositories mentioned [here](https://github.com/RoboTutorLLC/RoboTutor#xprize-submission) imply?

**Comment by JackMostow** [comment]
@sedflix - Please clarify:
1. Which GitHub repo, pointed by where?
2. Replace which step?
3. The XPRIZE repos mentioned are not yet public, but will be open-sourced at the end of the competition.
Thanks.  - Jack

**Comment by sedflix** [comment]
Oh, Sorry! I forgot to hyperlink "this" in the previous message. 

Right now, in the [Setup and Configuration](https://github.com/RoboTutorLLC/RoboTutor#setup-and-configuration) section it says, "The RTAsset_Publisher is the tool you can use to push the Rt assets ...". The "RTAsset_Publisher" points to `https://github.com/synaptek/RTAsset_Publisher`, which is either private or it doesn't exist. We could replace that link with `https://github.com/RoboTutorLLC/CodeDrop2_Assets`, which is public at the moment.

**Comment by JackMostow** [comment]
No links should point to synaptek, so I replaced it with RoboTutorLLC in this link in every branch, and verified that searching the RoboTutor repo for "synaptek" now finds nothing.  Thanks for catching it!

**Comment by sedflix** [comment]
Just to confirm, is [RoboTutorLLC/RTAsset_Publisher](https://github.com/RoboTutorLLC/RTAsset_Publisher) intentionally private?

**Comment by JackMostow** [comment]
Yes.  For now, the only public repos are for RoboTutor's runtime code and content.
