### ISSUE TITLE
3.1.6.1 make menu style a configuration variable

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#427]
Version 1.8.9.1 had the code drop 1 menu:
Kid picks content area (Reading & Writing, Stories, Numbers & Math, Redo, or Quit.
RoboTutor picks activity at kid's current level.

Version 2.7.7.1 has the code drop 2 menu:  
RoboTutor picks content area, cycling among Reading & Writing, Stories, Reading & Writing, Math.
Then kid picks among 2 activity icons, Redo, or Quit.

Version 3.1.6.1 reverted to the code drop 1 menu.

Revive the code drop 2 menu but as an alternative specified by a MenuStyle variable in config.json.
Values are "code drop 1" and "code drop 2".

**Comment by chengsyuan** [comment]
For the CD1, the config.json goes to:
```
{
 "config_version": "fttffENfCD1",
 "language_override": false,
 "show_tutorversion": true,
 "show_debug_launcher": true,
 "language_switcher": false,
 "no_asr_apps": false,
 "language_feature_id": "LANG_EN",
 "show_demo_vids": false,
 "menu_type": "CD1"
}
```
And here are the screenshots:
![image](https://user-images.githubusercontent.com/42427938/76302934-cfbffa80-62fb-11ea-96de-e4ca60882722.png)
![image](https://user-images.githubusercontent.com/42427938/76302918-c8005600-62fb-11ea-8dc8-2d8d9ce4df5b.png)


For the CD2, the config.json goes to:
```
{
 "config_version": "fttffENfCD2",
 "language_override": false,
 "show_tutorversion": true,
 "show_debug_launcher": true,
 "language_switcher": false,
 "no_asr_apps": false,
 "language_feature_id": "LANG_EN",
 "show_demo_vids": false,
 "menu_type": "CD2"
}
```
And here are the screenshots:
![image](https://user-images.githubusercontent.com/42427938/76302987-ebc39c00-62fb-11ea-961f-6e2335faa03b.png)
![image](https://user-images.githubusercontent.com/42427938/76303009-f4b46d80-62fb-11ea-9385-f0c497d67ae1.png)
