### ISSUE TITLE
Sentence writing tutor

### ISSUE THREAD

**Issue by JackMostow** [RoboTutorLLC/RoboTutor#88]
_From @JackMostow on February 2, 2017 2:21_

Sentence writing (see XPRIZE – Home > Design Discussion > FINGER WRITING > Writing Tutor > writing_tutor_20160726).
May be easier than punctuation tutor?

_Copied from original issue: synaptek/RoboTutor#225_

**Comment by kevindeland** [comment]
Completed in a previous commit.
